[[prompts]]
prompt = "Generate a complete code snippet in Ruby that defines a method to return 'Hello, World!'."
file_extension = "rb"

[[prompts]]
prompt = "Create a Python script that prints 'Hello, World!'."
file_extension = "py"

[[prompts]]
prompt = "Write a Java program that prints 'Hello, World!'."
file_extension = "java"

[[prompts]]
prompt = "Make a C program that returns 'Hello, World!'."
file_extension = "c"

[[prompts]]
prompt = "Write a JavaScript function that logs 'Hello, World!'."
file_extension = "js"

[[prompts]]
prompt = "Create a Go program that prints 'Hello, World!'."
file_extension = "go"

[[prompts]]
prompt = "Generate a PHP script that outputs 'Hello, World!'."
file_extension = "php"

[[prompts]]
prompt = "Write a C# program that displays 'Hello, World!'."
file_extension = "cs"

[[prompts]]
prompt = "Create a Swift function that returns 'Hello, World!'."
file_extension = "swift"

[[prompts]]
prompt = "Generate a Kotlin program that prints 'Hello, World!'."
file_extension = "kt"

[[prompts]]
prompt = "Write a Rust program that returns 'Hello, World!'."
file_extension = "rs"

[[prompts]]
prompt = "Make a TypeScript function that returns 'Hello, World!'."
file_extension = "ts"

[[prompts]]
prompt = "Create a R program that prints 'Hello, World!'."
file_extension = "R"

[[prompts]]
prompt = "Generate a Shell script that echoes 'Hello, World!'."
file_extension = "sh"

[[prompts]]
prompt = "Write a Lua script that prints 'Hello, World!'."
file_extension = "lua"

[[prompts]]
prompt = "Create a Perl script that outputs 'Hello, World!'."
file_extension = "pl"

[[prompts]]
prompt = "Make a Dart program that prints 'Hello, World!'."
file_extension = "dart"

[[prompts]]
prompt = "Generate a Haskell program that prints 'Hello, World!'."
file_extension = "hs"

[[prompts]]
prompt = "Write a Scala program that prints 'Hello, World!'."
file_extension = "scala"

[[prompts]]
prompt = "Create a Julia script that prints 'Hello, World!'."
file_extension = "jl"
